const Q=window.READER_QUIZ;
let current=0,maxReached=0,scores=Array(Q.questions.length).fill(null),states=[],locked=false,dragPayload=null;
const byId=id=>document.getElementById(id);
function blankState(q){
 if(q.type==='sceneSequence')return {order:Array(q.correct.length).fill(null)};
 if(q.type==='pictureTextMatch')return {slots:{},selected:null};
 if(q.type==='binaryGrid')return {answers:{}};
 if(q.type==='multiSelect')return {selected:[]};
 if(q.type==='wordOrder')return {order:[]};
 return {selected:null};
}
function resetStates(){states=Q.questions.map(blankState)}
function sprite(index,label,extra=''){const col=index%4,row=Math.floor(index/4);return `<div class="sprite ${extra}" role="img" aria-label="${label}"><img src="${Q.sprite}" alt="" draggable="false" style="--col:${col};--row:${row}"></div>`}
function init(){byId('quizLabel').textContent=`DECODABLE READER · ${Q.id}`;byId('coverTitle').textContent=Q.title;const subtitle=byId('coverSubtitle');if(subtitle){subtitle.textContent=Q.subtitle||'';subtitle.classList.toggle('hidden',!Q.subtitle)}byId('coverCopy').textContent=Q.coverCopy;byId('coverArt').innerHTML=Q.coverSprites.map(i=>sprite(i,Q.spriteLabels[i])).join('');byId('resultTitle').textContent=`${Q.title} complete!`;resetStates()}
function startQuiz(){resetStates();current=0;maxReached=0;scores=Array(Q.questions.length).fill(null);byId('cover').classList.add('hidden');byId('resultScreen').classList.add('hidden');byId('quizScreen').classList.remove('hidden');render()}
function render(){locked=scores[current]!==null;const q=Q.questions[current],fb=byId('feedback'),hintBtn=byId('hintBtn');renderProgress();byId('focusChip').textContent=`Q${current+1} · ${q.focus}`;byId('instruction').textContent=q.instruction;byId('hintText').textContent=q.hint;hintBtn.classList.remove('show');hintBtn.setAttribute('aria-expanded','false');fb.className='feedback';fb.textContent='';byId('checkBtn').classList.toggle('hidden',locked);byId('nextBtn').classList.toggle('hidden',!locked);byId('nextBtn').textContent=current===Q.questions.length-1?'See my stars →':'Next →';renderActivity(q)}
function renderProgress(){byId('progress').innerHTML=Q.questions.map((_,i)=>`<button type="button" class="step ${i===current?'active':''} ${scores[i]!==null?'done':''}" ${i>maxReached?'disabled':''} onclick="goToQuestion(${i})" aria-label="Go to question ${i+1}">${i+1}</button>`).join('');byId('miniScore').textContent=`${scores.filter(x=>x!==null).length} / ${Q.questions.length}`}
function goToQuestion(i){if(i>maxReached||i===current)return;current=i;render()}
function renderActivity(q){const a=byId('activity');if(q.type==='pictureTextMatch')renderMatch(q,a);else if(q.type==='binaryGrid')renderBinaryGrid(q,a);else if(q.type==='missingLetter')renderMissingLetter(q,a);else if(q.type==='clozeChoice')renderClozeChoice(q,a);else if(q.type==='multiSelect')renderMultiSelect(q,a);else if(q.type==='listenLetter')renderListenLetter(q,a);else if(q.type==='listenWord')renderListenWord(q,a);else if(q.type==='listenImage')renderListenImage(q,a);else if(q.type==='imageText')renderImageSentence(q,a);else if(q.type==='sceneSequence')renderSequence(q,a);else renderWordOrder(q,a)}
function sceneCard(item,inside=false){return `<button type="button" class="scene-card" ${locked?'disabled':''} draggable="${!locked}" ondragstart="beginDrag(event,'sequence','${item.id}')" onclick="${inside?`removeSequence('${item.id}')`:`placeSequence('${item.id}')`}">${sprite(item.sprite,item.label)}</button>`}
function renderSequence(q,a){const s=states[current];a.innerHTML=`<div class="sequence-slots">${s.order.map((id,i)=>`<div class="seq-slot" data-number="${i+1}" ondragover="allowDrop(event)" ondrop="dropSequence(event,${i})">${id?sceneCard(q.items.find(x=>x.id===id),true):''}</div>`).join('')}</div><div class="bank">${q.items.filter(x=>!s.order.includes(x.id)).map(x=>sceneCard(x)).join('')}</div>`}
function placeSequence(id,pos=null){if(locked)return;const s=states[current],old=s.order.indexOf(id);if(old>=0)s.order[old]=null;if(pos===null)pos=s.order.indexOf(null);if(pos>=0)s.order[pos]=id;renderActivity(Q.questions[current])}
function removeSequence(id){if(locked)return;const s=states[current],p=s.order.indexOf(id);if(p>=0)s.order[p]=null;renderActivity(Q.questions[current])}
function beginDrag(e,kind,id){dragPayload={kind,id};e.dataTransfer.setData('text/plain',id)}
function allowDrop(e){if(!locked)e.preventDefault()}
function dropSequence(e,pos){allowDrop(e);if(dragPayload?.kind==='sequence')placeSequence(dragPayload.id,pos);dragPayload=null}
function renderMatch(q,a){const s=states[current],used=Object.values(s.slots);a.innerHTML=`<div class="match-board">${q.pairs.map(p=>`<section class="match-row"><div>${sprite(p.sprite,p.label)}</div>${matchSlot(p.id,s,q)}</section>`).join('')}</div><div class="bank">${q.items.filter(x=>!used.includes(x.id)).map(item=>`<button type="button" class="sentence-card ${s.selected===item.id?'selected':''}" ${locked?'disabled':''} draggable="${!locked}" ondragstart="beginDrag(event,'match','${item.id}')" onclick="autoPlaceMatch('${item.id}')">${item.text}</button>`).join('')}</div>`}
function matchSlot(id,s,q){const item=q.items.find(x=>x.id===s.slots[id]);return `<button type="button" class="match-slot" ${locked?'disabled':''} aria-label="Sentence for ${id}" onclick="removeMatch('${id}')" ondragover="allowDrop(event)" ondrop="dropMatch(event,'${id}')">${item?`<span class="sentence-card placed">${item.text}</span>`:'?'}</button>`}
function autoPlaceMatch(id){if(locked)return;const q=Q.questions[current],s=states[current],empty=q.pairs.find(p=>!s.slots[p.id]);if(!empty)return;s.slots[empty.id]=id;renderActivity(q)}
function removeMatch(slot){if(locked)return;delete states[current].slots[slot];renderActivity(Q.questions[current])}
function dropMatch(e,slot){allowDrop(e);if(dragPayload?.kind==='match'){const s=states[current];Object.keys(s.slots).forEach(k=>{if(s.slots[k]===dragPayload.id)delete s.slots[k]});s.slots[slot]=dragPayload.id;renderActivity(Q.questions[current])}dragPayload=null}
function renderBinaryGrid(q,a){const s=states[current];a.innerHTML=`<div class="binary-grid">${q.items.map(item=>`<section class="binary-card"><div>${sprite(item.sprite,item.label)}</div><div class="binary-options">${q.options.map(option=>`<button type="button" class="binary-option ${s.answers[item.id]===option?'selected':''}" ${locked?'disabled':''} onclick="chooseBinary('${item.id}','${option.replace(/'/g,"\\'")}')">${option}</button>`).join('')}</div></section>`).join('')}</div>`}
function chooseBinary(id,value){if(locked)return;states[current].answers[id]=value;renderActivity(Q.questions[current])}
function renderMissingLetter(q,a){const s=states[current];a.innerHTML=`<div class="missing-wrap"><div class="missing-picture">${sprite(q.picture,q.pictureLabel)}</div><div><div class="missing-word" aria-label="${q.accessibleWord}">${q.before}<button type="button" class="missing-slot" ${locked?'disabled':''} onclick="removeMissing()" aria-label="Missing letter">${s.selected||''}</button>${q.after}</div><div class="letter-choice-grid">${q.options.filter(o=>o!==s.selected).map(o=>`<button type="button" class="letter-choice" ${locked?'disabled':''} onclick="choose('${o}')">${o}</button>`).join('')}</div></div></div>`}
function removeMissing(){if(locked)return;states[current].selected=null;renderActivity(Q.questions[current])}
function renderClozeChoice(q,a){const s=states[current],parts=q.prompt.split('___');a.innerHTML=`<div class="cloze-wrap">${q.picture===undefined?'':`<div class="cloze-picture">${sprite(q.picture,q.pictureLabel)}</div>`}<div class="cloze-sentence">${parts[0]}<button type="button" class="cloze-blank" ${locked?'disabled':''} onclick="removeCloze()" aria-label="Missing word">${s.selected||''}</button>${parts[1]}</div><div class="cloze-options">${q.options.filter(o=>o!==s.selected).map(o=>`<button type="button" class="cloze-option" ${locked?'disabled':''} onclick="choose('${o.replace(/'/g,"\\'")}')">${o}</button>`).join('')}</div></div>`}
function removeCloze(){if(locked)return;states[current].selected=null;renderActivity(Q.questions[current])}
function renderMultiSelect(q,a){const s=states[current];a.innerHTML=`<div class="multi-grid">${q.options.map(o=>`<button type="button" class="multi-option ${s.selected.includes(o.id)?'selected':''}" ${locked?'disabled':''} onclick="toggleMulti('${o.id}')">${o.text}</button>`).join('')}</div>`}
function toggleMulti(id){if(locked)return;const selected=states[current].selected,p=selected.indexOf(id);if(p>=0)selected.splice(p,1);else selected.push(id);renderActivity(Q.questions[current])}
function speaker(text,audio,balanced=false,maxDuration=0){const action=audio?`playAudio('${audio}',${maxDuration})`:`speak('${text.replace(/'/g,"\\'")}')`;return `<div class="listen-row ${balanced?'balanced':''}"><button type="button" class="speaker" onclick="${action}" aria-label="Play audio">🔊</button></div>`}
function renderListenLetter(q,a){const s=states[current];a.innerHTML=`${speaker(q.speech,q.audio,q.balancedSpeaker,q.maxAudioDuration)}<div class="vowel-options">${q.options.map(o=>`<button type="button" class="vowel-card ${s.selected===o?'selected':''}" ${locked?'disabled':''} onclick="choose('${o}')">${o}</button>`).join('')}</div>`}
function renderListenWord(q,a){const s=states[current];a.innerHTML=`${speaker(q.speech,q.audio,q.balancedSpeaker,q.maxAudioDuration)}<div class="word-options">${q.options.map(o=>`<button type="button" class="word-option ${s.selected===o?'selected':''}" ${locked?'disabled':''} onclick="choose('${o.replace(/'/g,"\\'")}')">${o}</button>`).join('')}</div>`}
function renderListenImage(q,a){const s=states[current];a.innerHTML=`${speaker(q.speech,q.audio,q.balancedSpeaker,q.maxAudioDuration)}<div class="image-options">${q.options.map(o=>`<button type="button" class="image-option ${s.selected===o.id?'selected':''}" ${locked?'disabled':''} onclick="choose('${o.id}')">${sprite(o.sprite,o.label)}</button>`).join('')}</div>`}
function renderWordOrder(q,a){const s=states[current];a.innerHTML=`<div class="order-wrap"><div>${sprite(q.picture,q.pictureLabel,'order-picture')}</div><div><div class="word-well">${s.order.map(id=>{const item=q.items.find(x=>x.id===id);return `<button type="button" class="word-tile" ${locked?'disabled':''} onclick="removeWord('${id}')">${item.text}</button>`}).join('')}</div><div class="word-bank">${q.items.filter(x=>!s.order.includes(x.id)).map(item=>`<button type="button" class="word-tile" ${locked?'disabled':''} onclick="addWord('${item.id}')">${item.text}</button>`).join('')}</div></div></div>`}
function addWord(id){if(locked)return;states[current].order.push(id);renderActivity(Q.questions[current])}
function removeWord(id){if(locked)return;const p=states[current].order.indexOf(id);if(p>=0)states[current].order.splice(p,1);renderActivity(Q.questions[current])}
function renderImageSentence(q,a){const s=states[current];a.innerHTML=`<div class="picture-sentence ${q.wideCards?'wide-sentence-cards':''}"><div>${sprite(q.picture,q.pictureLabel,'big-picture')}</div><div class="sentence-options">${q.options.map(o=>`<button type="button" class="sentence-option ${s.selected===o.id?'selected':''}" ${locked?'disabled':''} onclick="choose('${o.id}')">${o.text}</button>`).join('')}</div></div>`}
function choose(id){if(locked)return;states[current].selected=id;renderActivity(Q.questions[current])}
let audioPlayer=null,audioStopTimer=null;
function playAudio(src,maxDuration=0){if(audioStopTimer)clearTimeout(audioStopTimer);if(audioPlayer)audioPlayer.pause();audioPlayer=new Audio(src);audioPlayer.play().then(()=>{if(maxDuration>0)audioStopTimer=setTimeout(()=>{audioPlayer.pause();audioPlayer.currentTime=0},maxDuration*1000)}).catch(()=>alert('Please check your sound and try again.'))}
function speak(text){if(!('speechSynthesis'in window)){alert(text);return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.72;u.pitch=1.04;const voices=speechSynthesis.getVoices();u.voice=voices.find(v=>v.lang.startsWith('en')&&/female|samantha|zira|ava/i.test(v.name))||voices.find(v=>v.lang.startsWith('en'))||null;speechSynthesis.speak(u)}
function scoreCurrent(q){const s=states[current];if(q.type==='pictureTextMatch'){if(q.pairs.some(p=>!s.slots[p.id]))return null;let got=0;q.pairs.forEach(p=>{got+=s.slots[p.id]===p.correct?1:0});return Math.round(got/q.pairs.length*100)}if(q.type==='binaryGrid'){if(q.items.some(item=>!s.answers[item.id]))return null;return Math.round(q.items.filter(item=>s.answers[item.id]===item.correct).length/q.items.length*100)}if(q.type==='multiSelect'){if(!s.selected.length)return null;const correct=q.options.filter(o=>o.correct).map(o=>o.id),hits=s.selected.filter(id=>correct.includes(id)).length,falsePos=s.selected.filter(id=>!correct.includes(id)).length;return Math.round(Math.max(0,hits-falsePos)/correct.length*100)}if(q.type==='missingLetter'||q.type==='clozeChoice'||q.type==='listenWord'||q.type==='listenLetter'){if(!s.selected)return null;return s.selected===q.correct?100:0}if(q.type==='sceneSequence'){if(s.order.some(x=>!x))return null;let got=0;q.correct.forEach((id,pos)=>{const placed=s.order.indexOf(id),d=Math.abs(placed-pos);got+=d===0?1:d===1?.5:0});return Math.round(got/q.correct.length*100)}if(q.type==='wordOrder'){if(s.order.length!==q.correct.length)return null;return Math.round(s.order.filter((id,i)=>id===q.correct[i]).length/q.correct.length*100)}if(!s.selected)return null;return q.options.find(x=>x.id===s.selected)?.score??0}
function checkAnswer(){const q=Q.questions[current],score=scoreCurrent(q),fb=byId('feedback');if(score===null){fb.className='feedback show try';fb.textContent='Finish this reading step first.';return}scores[current]=score;locked=true;fb.className=`feedback show ${score>=67?'good':'try'}`;fb.textContent=score===100?'⭐ Great reading!':score>=67?'👍 Almost there — you found the main clue.':'🌱 Good try — use the hint and read it slowly.';byId('checkBtn').classList.add('hidden');byId('nextBtn').classList.remove('hidden');renderProgress();renderActivity(q)}
function toggleHint(){const btn=byId('hintBtn'),show=!btn.classList.contains('show');btn.classList.toggle('show',show);btn.setAttribute('aria-expanded',String(show))}
function nextQuestion(){if(current<Q.questions.length-1){current++;maxReached=Math.max(maxReached,current);render()}else showResults()}
function showResults(){byId('quizScreen').classList.add('hidden');byId('resultScreen').classList.remove('hidden');const total=Math.round(scores.reduce((a,b)=>a+(b||0),0)/Q.questions.length);byId('totalScore').textContent=`${total} / 100`;byId('resultCopy').textContent=total>=85?'You connected sounds, pictures, words, and patterns!':total>=60?'You found many decoding clues. One more round will make them stronger!':'Say each target word slowly, then try one more time.';byId('resultGrid').innerHTML=Q.questions.map((q,i)=>`<div class="result-item"><strong>Q${i+1} · ${q.focus}</strong><span>${scores[i]}%</span></div>`).join('')}
function restartQuiz(){startQuiz()}
init();
